person:
  name: 狗古珊@qq.com
server:
  port: 8088
spring:
  profiles:
    active:
---
server:
  port: 8083
spring:
  profiles: dev
  thymeleaf:
    cache: false
---
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/wage-management-sys?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
   username: root
   password: 123456
   driver-class-name: com.mysql.cj.jdbc.Driver
   type: com.alibaba.druid.pool.DruidDataSource
   filters: stat,wall,log4j

---

---
redis:
      ip: 192.168.96.10
      port: 6379
      pass: 123456
---
spring:
  redis:
    host: 192.168.96.10
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
    database: 0
---
logging:
  level:
    root: info
    com.oyhj.sys.mapper.*: debug
---
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.oyhj.*.entity